FROM node:18-slim  as server-dependencies

RUN apt update \
  && apt install -y build-essential python3

WORKDIR /app/client
COPY package.json package-lock.json /app/client/
RUN npm install npm@latest --global && npm install pnpm --global && pnpm import && pnpm install


WORKDIR /app/
COPY ../../package.json ../../package-lock.json /app/
RUN pnpm import && pnpm install
